// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as CLONE_FACTORY_ADDR,
    BYTECODE_HASH as CLONE_FACTORY_HASH
} from "../generated/candidate/CloneFactory.sol";

/// @title LibCloneFactoryDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `CloneFactory`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibCloneFactoryDeploy {
    address constant CLONE_FACTORY_DEPLOYED_ADDRESS = CLONE_FACTORY_ADDR;
    bytes32 constant CLONE_FACTORY_DEPLOYED_CODEHASH = CLONE_FACTORY_HASH;
}
