// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY ./script/BuildPointers.sol

import {
    DEPLOYED_ADDRESS as CLONE_FACTORY_ADDR,
    BYTECODE_HASH as CLONE_FACTORY_HASH
} from "../generated/0_1_5/CloneFactory.pointers.sol";

/// @title LibCloneFactoryDeploy
/// @notice The deterministic Zoltu deploy address and code hash of the current
/// `CloneFactory` release, aliased from the frozen per-release snapshot in
/// `src/generated/<tag>/CloneFactory.pointers.sol` so that snapshot stays the
/// single source of truth. Lets consumers verify/deploy against a precommitted
/// address + hash rather than a registry.
library LibCloneFactoryDeploy {
    address constant CLONE_FACTORY_DEPLOYED_ADDRESS = CLONE_FACTORY_ADDR;
    bytes32 constant CLONE_FACTORY_DEPLOYED_CODEHASH = CLONE_FACTORY_HASH;
}
