// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Script} from "forge-std-1.16.1/src/Script.sol";
import {LibCodeGen} from "rain-sol-codegen-0.1.0/src/lib/LibCodeGen.sol";
import {LibFs} from "rain-sol-codegen-0.1.0/src/lib/LibFs.sol";
import {LibRainDeploy} from "rain-deploy-0.1.3/src/lib/LibRainDeploy.sol";
import {CloneFactory} from "../src/concrete/CloneFactory.sol";

/// @title BuildPointers
/// @notice Generates the deterministic-deploy pins for `CloneFactory`:
///   1. A frozen per-release snapshot `src/generated/<tag>/CloneFactory.pointers.sol`
///      (`BYTECODE_HASH`, `DEPLOYED_ADDRESS`, `CREATION_CODE`, `RUNTIME_CODE`) for
///      the current `deployTag()`. Historical tags are never regenerated; a
///      release bump writes a new `<tag>/` snapshot beside them.
///   2. `src/lib/LibCloneFactoryDeploy.sol` — the current-release address and
///      codehash, aliased from the current `deployTag()` snapshot so that
///      snapshot stays the single source of truth (never a duplicated literal).
///      Kept in `src/lib` so consumers' import path is stable across releases.
///
/// Run as `forge script script/BuildPointers.sol`. Wired into the autopublish
/// `soldeer-generate-cmd` so the pins regenerate born-green on each release.
contract BuildPointers is Script {
    string constant GEN_LIB_PATH = "src/lib/LibCloneFactoryDeploy.sol";

    // REUSE-IgnoreStart  (the two SPDX lines below are the header EMITTED into the
    // generated lib, not this script's own license — hide from reuse lint)
    string constant GEN_SPDX_LICENSE = "// SPDX-License-Identifier: LicenseRef-DCL-1.0";
    string constant GEN_SPDX_COPYRIGHT = "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd";

    // REUSE-IgnoreEnd

    /// @notice The canonical release tag. Read from `foundry.toml`
    /// `[package].version` — the single source of truth — with dots converted to
    /// underscores for the Solidity dir form (`0.1.3` -> `0_1_3`).
    function deployTag() internal view returns (string memory) {
        string memory version = vm.parseTomlString(vm.readFile("foundry.toml"), ".package.version");
        bytes memory b = bytes(version);
        bytes memory out = new bytes(b.length);
        for (uint256 i = 0; i < b.length; i++) {
            out[i] = b[i] == "." ? bytes1("_") : b[i];
        }
        return string(out);
    }

    function addressConstantString(address addr) internal pure returns (string memory) {
        return string.concat(
            "\n",
            "/// @dev The deterministic deploy address of the contract when deployed via\n",
            "/// the Zoltu factory.\n",
            "address constant DEPLOYED_ADDRESS = address(",
            vm.toString(addr),
            ");\n"
        );
    }

    function run() external {
        LibRainDeploy.etchZoltuFactory(vm);

        // A fresh next-version slot has no `<tag>/` dir yet, and `vm.writeFile`
        // won't create one.
        vm.createDir(string.concat("src/generated/", deployTag()), true);

        bytes memory creationCode = type(CloneFactory).creationCode;
        address deployed = LibRainDeploy.deployZoltu(creationCode);

        // Frozen per-tag snapshot.
        LibFs.buildFileForContract(
            vm,
            deployed,
            string.concat(deployTag(), "/CloneFactory"),
            string.concat(
                addressConstantString(deployed),
                LibCodeGen.bytesConstantString(
                    vm, "/// @dev The creation bytecode of the contract.", "CREATION_CODE", creationCode
                ),
                LibCodeGen.bytesConstantString(
                    vm, "/// @dev The runtime bytecode of the contract.", "RUNTIME_CODE", deployed.code
                )
            )
        );

        // Current-release pin lib.
        genLibCloneFactoryDeploy();
    }

    /// @notice (Re)generate `src/lib/LibCloneFactoryDeploy.sol`, aliasing the
    /// current `deployTag()` snapshot's `DEPLOYED_ADDRESS` + `BYTECODE_HASH` as
    /// the current-release constants — the snapshot stays the single source of
    /// truth (never a duplicated literal). Emitted line-by-line to match the
    /// generated-file convention.
    function genLibCloneFactoryDeploy() internal {
        string memory importPath = string.concat("../generated/", deployTag(), "/CloneFactory.pointers.sol");
        vm.writeFile(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, GEN_SPDX_LICENSE);
        vm.writeLine(GEN_LIB_PATH, GEN_SPDX_COPYRIGHT);
        vm.writeLine(GEN_LIB_PATH, "pragma solidity ^0.8.25;");
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "// THIS FILE IS AUTOGENERATED BY ./script/BuildPointers.sol");
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "import {");
        vm.writeLine(GEN_LIB_PATH, "    DEPLOYED_ADDRESS as CLONE_FACTORY_ADDR,");
        vm.writeLine(GEN_LIB_PATH, "    BYTECODE_HASH as CLONE_FACTORY_HASH");
        vm.writeLine(GEN_LIB_PATH, string.concat("} from \"", importPath, "\";"));
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "/// @title LibCloneFactoryDeploy");
        vm.writeLine(GEN_LIB_PATH, "/// @notice The deterministic Zoltu deploy address and code hash of the current");
        vm.writeLine(GEN_LIB_PATH, "/// `CloneFactory` release, aliased from the frozen per-release snapshot in");
        vm.writeLine(GEN_LIB_PATH, "/// `src/generated/<tag>/CloneFactory.pointers.sol` so that snapshot stays the");
        vm.writeLine(GEN_LIB_PATH, "/// single source of truth. Lets consumers verify/deploy against a precommitted");
        vm.writeLine(GEN_LIB_PATH, "/// address + hash rather than a registry.");
        vm.writeLine(GEN_LIB_PATH, "library LibCloneFactoryDeploy {");
        vm.writeLine(GEN_LIB_PATH, "    address constant CLONE_FACTORY_DEPLOYED_ADDRESS = CLONE_FACTORY_ADDR;");
        vm.writeLine(GEN_LIB_PATH, "    bytes32 constant CLONE_FACTORY_DEPLOYED_CODEHASH = CLONE_FACTORY_HASH;");
        vm.writeLine(GEN_LIB_PATH, "}");
    }
}
