// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Script} from "forge-std-1.16.1/src/Script.sol";
import {LibCodeGen} from "rain-sol-codegen-0.1.0/src/lib/LibCodeGen.sol";
import {LibFs} from "rain-sol-codegen-0.1.0/src/lib/LibFs.sol";
import {LibRainDeploy} from "rain-deploy-0.1.3/src/lib/LibRainDeploy.sol";
import {CloneFactory} from "../src/concrete/CloneFactory.sol";

/// @title BuildPointers
/// @notice Generates the deterministic-deploy pins for `CloneFactory`:
///   1. The rolling `src/generated/candidate/CloneFactory.pointers.sol` snapshot
///      (`BYTECODE_HASH`, `DEPLOYED_ADDRESS`, `CREATION_CODE`, `RUNTIME_CODE`) of
///      whatever the current source compiles to. Regenerated in full on every
///      run; committed so tests can assert source and snapshot agree.
///   2. `src/lib/LibCloneFactoryDeploy.sol` — the address and codehash consumers
///      import, aliased from the `candidate` snapshot so that snapshot stays the
///      single source of truth (never a duplicated literal). Kept in `src/lib` so
///      consumers' import path is stable across releases.
///
/// Numbered snapshots (`src/generated/0_1_5/`, …) are frozen release records.
/// This script never writes one and never reads one: the only thing that creates
/// a numbered dir is `script/cut-release.sh` copying `candidate` at release time.
///
/// Run as `forge script script/BuildPointers.sol`.
contract BuildPointers is Script {
    string constant GEN_LIB_PATH = "src/lib/LibCloneFactoryDeploy.sol";

    // REUSE-IgnoreStart  (the two SPDX lines below are the header EMITTED into the
    // generated lib, not this script's own license — hide from reuse lint)
    string constant GEN_SPDX_LICENSE = "// SPDX-License-Identifier: LicenseRef-DCL-1.0";
    string constant GEN_SPDX_COPYRIGHT = "// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd";

    // REUSE-IgnoreEnd

    /// @notice The rolling "current source" snapshot tag — always `candidate`,
    /// never a version number. `src/generated/candidate/` is regenerated from the
    /// current source on every run, so `LibCloneFactoryDeploy` tracks whatever the
    /// source currently compiles to. A numbered snapshot is frozen only when a
    /// release tag promotes `candidate` (see `script/cut-release.sh`), and is
    /// never regenerated here.
    string constant CANDIDATE_TAG = "candidate";

    function deployTag() internal pure returns (string memory) {
        return CANDIDATE_TAG;
    }

    function addressConstantString(address addr) internal pure returns (string memory) {
        return string.concat(
            "\n",
            "/// @dev The deterministic deploy address of the contract when deployed via\n",
            "/// the Zoltu factory.\n",
            "address constant DEPLOYED_ADDRESS = address(",
            vm.toString(addr),
            ");\n"
        );
    }

    function run() external {
        LibRainDeploy.etchZoltuFactory(vm);

        // A fresh checkout that has never generated has no `candidate/` dir yet,
        // and `vm.writeFile` won't create one.
        vm.createDir(string.concat("src/generated/", deployTag()), true);

        bytes memory creationCode = type(CloneFactory).creationCode;
        address deployed = LibRainDeploy.deployZoltu(creationCode);

        // Rolling `candidate` snapshot of the current source.
        LibFs.buildFileForContract(
            vm,
            deployed,
            string.concat(deployTag(), "/CloneFactory"),
            string.concat(
                addressConstantString(deployed),
                LibCodeGen.bytesConstantString(
                    vm, "/// @dev The creation bytecode of the contract.", "CREATION_CODE", creationCode
                ),
                LibCodeGen.bytesConstantString(
                    vm, "/// @dev The runtime bytecode of the contract.", "RUNTIME_CODE", deployed.code
                )
            )
        );

        // Consumer-facing pin lib.
        genLibCloneFactoryDeploy();
    }

    /// @notice (Re)generate `src/lib/LibCloneFactoryDeploy.sol`, aliasing the
    /// `candidate` snapshot's `DEPLOYED_ADDRESS` + `BYTECODE_HASH` as the
    /// consumer-facing constants — the snapshot stays the single source of truth
    /// (never a duplicated literal). Emitted line-by-line to match the
    /// generated-file convention.
    function genLibCloneFactoryDeploy() internal {
        string memory importPath = string.concat("../generated/", deployTag(), "/CloneFactory.pointers.sol");
        vm.writeFile(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, GEN_SPDX_LICENSE);
        vm.writeLine(GEN_LIB_PATH, GEN_SPDX_COPYRIGHT);
        vm.writeLine(GEN_LIB_PATH, "pragma solidity ^0.8.25;");
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "// THIS FILE IS AUTOGENERATED BY ./script/BuildPointers.sol");
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "import {");
        vm.writeLine(GEN_LIB_PATH, "    DEPLOYED_ADDRESS as CLONE_FACTORY_ADDR,");
        vm.writeLine(GEN_LIB_PATH, "    BYTECODE_HASH as CLONE_FACTORY_HASH");
        vm.writeLine(GEN_LIB_PATH, string.concat("} from \"", importPath, "\";"));
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "/// @title LibCloneFactoryDeploy");
        vm.writeLine(GEN_LIB_PATH, "/// @notice The deterministic Zoltu deploy address and code hash of the");
        vm.writeLine(GEN_LIB_PATH, "/// `CloneFactory` the current source compiles to, aliased from the rolling");
        vm.writeLine(GEN_LIB_PATH, "/// `src/generated/candidate/CloneFactory.pointers.sol` snapshot so that snapshot");
        vm.writeLine(GEN_LIB_PATH, "/// stays the single source of truth. Lets consumers verify/deploy against a");
        vm.writeLine(GEN_LIB_PATH, "/// precommitted address + hash rather than a registry. A published release is a");
        vm.writeLine(GEN_LIB_PATH, "/// frozen copy of these bytes, so a consumer pinning a Soldeer version gets an");
        vm.writeLine(GEN_LIB_PATH, "/// immutable pin even though `candidate` rolls on `main`.");
        vm.writeLine(GEN_LIB_PATH, "library LibCloneFactoryDeploy {");
        vm.writeLine(GEN_LIB_PATH, "    /// @dev The snapshot dir these constants are aliased from. Always the");
        vm.writeLine(GEN_LIB_PATH, "    /// rolling `candidate`, never a version number.");
        vm.writeLine(GEN_LIB_PATH, string.concat("    string constant DEPLOY_TAG = \"", deployTag(), "\";"));
        vm.writeLine(GEN_LIB_PATH, "");
        vm.writeLine(GEN_LIB_PATH, "    address constant CLONE_FACTORY_DEPLOYED_ADDRESS = CLONE_FACTORY_ADDR;");
        vm.writeLine(GEN_LIB_PATH, "    bytes32 constant CLONE_FACTORY_DEPLOYED_CODEHASH = CLONE_FACTORY_HASH;");
        vm.writeLine(GEN_LIB_PATH, "}");
    }
}
